/**
 * SyntaxHighlighter
 * http://alexgorbatchev.com/
 *
 * SyntaxHighlighter is donationware. If you are using it, please donate.
 * http://alexgorbatchev.com/wiki/SyntaxHighlighter:Donate
 *
 * @version
 * 2.1.364 (October 15 2009)
 * 
 * @copyright
 * Copyright (C) 2004-2009 Alex Gorbatchev.
 *
 * @license
 * This file is part of SyntaxHighlighter.
 * 
 * SyntaxHighlighter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * SyntaxHighlighter is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SyntaxHighlighter.  If not, see <http://www.gnu.org/copyleft/lesser.html>.
 *
 * Unfortunately I don't know how to use the orgional compiler, so this has been compiled with the Closure Compiler from http://closure-compiler.appspot.com/home -- AndrewJones
 */
if(!window.SyntaxHighlighter)var SyntaxHighlighter=function(){var e={defaults:{"class-name":"","first-line":1,"pad-line-numbers":true,highlight:null,"smart-tabs":true,"tab-size":4,gutter:true,toolbar:true,collapse:false,"auto-links":true,light:false,"wrap-lines":true,"html-script":false},config:{useScriptTags:true,clipboardSwf:null,toolbarItemWidth:16,toolbarItemHeight:16,bloggerMode:false,stripBrs:false,tagName:"pre",strings:{expandSource:"show source",viewSource:"view source",copyToClipboard:"copy to clipboard",
copyToClipboardConfirmation:"The code is in your clipboard now",print:"print",help:"?",alert:"SyntaxHighlighter\n\n",noBrush:"Can't find brush for: ",brushNotHtmlScript:"Brush wasn't configured for html-script option: ",aboutDialog:'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>About SyntaxHighlighter</title></head><body style="font-family:Geneva,Arial,Helvetica,sans-serif;background-color:#fff;color:#000;font-size:1em;text-align:center;"><div style="text-align:center;margin-top:3em;"><div style="font-size:xx-large;">SyntaxHighlighter</div><div style="font-size:.75em;margin-bottom:4em;"><div>version 2.1.364 (October 15 2009)</div><div><a href="http://alexgorbatchev.com" target="_blank" style="color:#0099FF;text-decoration:none;">http://alexgorbatchev.com</a></div><div>If you like this script, please <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2930402" style="color:#0099FF;text-decoration:none;">donate</a> to keep development active!</div></div><div>JavaScript code syntax highlighter.</div><div>Copyright 2004-2009 Alex Gorbatchev.</div></div></body></html>'},
debug:false},vars:{discoveredBrushes:null,spaceWidth:null,printFrame:null,highlighters:{}},brushes:{},regexLib:{multiLineCComments:/\/\*[\s\S]*?\*\//gm,singleLineCComments:/\/\/.*$/gm,singleLinePerlComments:/#.*$/gm,doubleQuotedString:/"([^\\"\n]|\\.)*"/g,singleQuotedString:/'([^\\'\n]|\\.)*'/g,multiLineDoubleQuotedString:/"([^\\"]|\\.)*"/g,multiLineSingleQuotedString:/'([^\\']|\\.)*'/g,xmlComments:/(&lt;|<)!--[\s\S]*?--(&gt;|>)/gm,url:/&lt;\w+:\/\/[\w-.\/?%&=@:;]*&gt;|\w+:\/\/[\w-.\/?%&=@:;]*/g,
phpScriptTags:{left:/(&lt;|<)\?=?/g,right:/\?(&gt;|>)/g},aspScriptTags:{left:/(&lt;|<)%=?/g,right:/%(&gt;|>)/g},scriptScriptTags:{left:/(&lt;|<)\s*script.*?(&gt;|>)/gi,right:/(&lt;|<)\/\s*script\s*(&gt;|>)/gi}},toolbar:{create:function(a){var b=document.createElement("DIV"),c=e.toolbar.items;b.className="toolbar";for(var d in c){var f=c[d];f=new f(a);if(f.create){var g=f.create();a.toolbarCommands[d]=f;if(g!=null){if(typeof g=="string")g=e.toolbar.createButton(g,a.id,d);g.className+="item "+d;b.appendChild(g)}}}return b},
createButton:function(a,b,c){var d=document.createElement("a"),f=d.style,g=e.config,h=g.toolbarItemWidth;g=g.toolbarItemHeight;d.href="#"+c;d.title=a;d.highlighterId=b;d.commandName=c;d.innerHTML=a;if(isNaN(h)==false)f.width=h+"px";if(isNaN(g)==false)f.height=g+"px";d.onclick=function(k){try{e.toolbar.executeCommand(this,k||window.event,this.highlighterId,this.commandName)}catch(i){e.utils.alert(i.message)}return false};return d},executeCommand:function(a,b,c,d,f){c=e.vars.highlighters[c];var g;if(c==
null||(g=c.toolbarCommands[d])==null)return null;return g.execute(a,b,f)},items:{expandSource:function(a){this.create=function(){if(a.getParam("collapse")==true)return e.config.strings.expandSource};this.execute=function(b){var c=a.div;b.parentNode.removeChild(b);c.className=c.className.replace("collapsed","")}},viewSource:function(a){this.create=function(){return e.config.strings.viewSource};this.execute=function(){var b=e.utils.fixInputString(a.originalCode).replace(/</g,"&lt;"),c=e.utils.popup("",
"_blank",750,400,"location=0, resizable=1, menubar=0, scrollbars=1");b=e.utils.unindent(b);c.document.write("<pre>"+b+"</pre>");c.document.close()}},copyToClipboard:function(a){var b,c=a.id;this.create=function(){var d=e.config;if(d.clipboardSwf==null)return null;function f(i){var m="";for(var l in i)m+="<param name='"+l+"' value='"+i[l]+"'/>";return m}function g(i){var m="";for(var l in i)m+=" "+l+"='"+i[l]+"'";return m}var h={width:d.toolbarItemWidth,height:d.toolbarItemHeight,id:c+"_clipboard",
type:"application/x-shockwave-flash",title:e.config.strings.copyToClipboard},k={allowScriptAccess:"always",wmode:"transparent",flashVars:"highlighterId="+c,menu:"false"};d=d.clipboardSwf;h=/msie/i.test(navigator.userAgent)?"<object"+g({classid:"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000",codebase:"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0"})+g(h)+">"+f(k)+f({movie:d})+"</object>":"<embed"+g(h)+g(k)+g({src:d})+"/>";b=document.createElement("div");b.innerHTML=
h;return b};this.execute=function(d,f,g){d=g.command;switch(d){case "get":g=e.utils.unindent(e.utils.fixInputString(a.originalCode).replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&"));if(window.clipboardData)window.clipboardData.setData("text",g);else return e.utils.unindent(g);case "ok":e.utils.alert(e.config.strings.copyToClipboardConfirmation);break;case "error":e.utils.alert(g.message);break}}},printSource:function(a){this.create=function(){return e.config.strings.print};this.execute=
function(){var b=document.createElement("IFRAME"),c=null;e.vars.printFrame!=null&&document.body.removeChild(e.vars.printFrame);e.vars.printFrame=b;b.style.cssText="position:absolute;width:0px;height:0px;left:-500px;top:-500px;";document.body.appendChild(b);c=b.contentWindow.document;d(c,window.document);c.write('<div class="'+a.div.className.replace("collapsed","")+' printing">'+a.div.innerHTML+"</div>");c.close();b.contentWindow.focus();b.contentWindow.print();function d(f,g){g=g.getElementsByTagName("link");
for(var h=0;h<g.length;h++)g[h].rel.toLowerCase()=="stylesheet"&&/shCore\.css$/.test(g[h].href)&&f.write('<link type="text/css" rel="stylesheet" href="'+g[h].href+'"></link>')}}},about:function(){this.create=function(){return e.config.strings.help};this.execute=function(){var a=e.utils.popup("","_blank",500,250,"scrollbars=0"),b=a.document;b.write(e.config.strings.aboutDialog);b.close();a.focus()}}}},utils:{indexOf:function(a,b,c){for(c=c=Math.max(c||0,0);c<a.length;c++)if(a[c]==b)return c;return-1},
guid:function(a){return a+Math.round(Math.random()*1000000).toString()},merge:function(a,b){var c={},d;for(d in a)c[d]=a[d];for(d in b)c[d]=b[d];return c},toBoolean:function(a){switch(a){case "true":return true;case "false":return false}return a},popup:function(a,b,c,d,f){var g=(screen.width-c)/2,h=(screen.height-d)/2;f+=", left="+g+", top="+h+", width="+c+", height="+d;f=f.replace(/^,/,"");a=window.open(a,b,f);a.focus();return a},addEvent:function(a,b,c){if(a.attachEvent){a["e"+b+c]=c;a[b+c]=function(){a["e"+
b+c](window.event)};a.attachEvent("on"+b,a[b+c])}else a.addEventListener(b,c,false)},alert:function(a){alert(e.config.strings.alert+a)},findBrush:function(a,b){var c=e.vars.discoveredBrushes,d=null;if(c==null){c={};for(var f in e.brushes){d=e.brushes[f].aliases;if(d!=null){e.brushes[f].name=f.toLowerCase();for(var g=0;g<d.length;g++)c[d[g]]=f}}e.vars.discoveredBrushes=c}d=e.brushes[c[a]];d==null&&b!=false&&e.utils.alert(e.config.strings.noBrush+a);return d},eachLine:function(a,b){a=a.split("\n");
for(var c=0;c<a.length;c++)a[c]=b(a[c]);return a.join("\n")},trimFirstAndLastLines:function(a){return a.replace(/^[ ]*[\n]+|[\n]*[ ]*$/g,"")},parseParams:function(a){for(var b,c={},d=new XRegExp("^\\[(?<values>(.*?))\\]$"),f=new XRegExp("(?<name>[\\w-]+)\\s*:\\s*(?<value>[\\w-%#]+|\\[.*?\\]|\".*?\"|'.*?')\\s*;?","g");(b=f.exec(a))!=null;){var g=b.value.replace(/^['"]|['"]$/g,"");if(g!=null&&d.test(g)){g=d.exec(g);g=g.values.length>0?g.values.split(/\s*,\s*/):[]}c[b.name]=g}return c},decorate:function(a,
b){if(a==null||a.length==0||a=="\n")return a;a=a.replace(/</g,"&lt;");a=a.replace(/ {2,}/g,function(c){for(var d="",f=0;f<c.length-1;f++)d+="&nbsp;";return d+" "});if(b!=null)a=e.utils.eachLine(a,function(c){if(c.length==0)return"";var d="";c=c.replace(/^(&nbsp;| )+/,function(f){d=f;return""});if(c.length==0)return d;return d+'<code class="'+b+'">'+c+"</code>"});return a},padNumber:function(a,b){for(a=a.toString();a.length<b;)a="0"+a;return a},measureSpace:function(){var a=document.createElement("div"),
b;b=0;var c=document.body;b=e.utils.guid("measureSpace");var d='<div class="',f="</div>",g="</span>";a.innerHTML=d+'syntaxhighlighter">'+d+'lines">'+d+'line">'+d+'content"><span class="block"><span id="'+b+'">&nbsp;'+g+g+f+f+f+f;c.appendChild(a);b=document.getElementById(b);if(/opera/i.test(navigator.userAgent)){b=window.getComputedStyle(b,null);b=parseInt(b.getPropertyValue("width"))}else b=b.offsetWidth;c.removeChild(a);return b},processTabs:function(a,b){for(var c="",d=0;d<b;d++)c+=" ";return a.replace(/\t/g,
c)},processSmartTabs:function(a,b){a.split("\n");for(var c="\t",d="",f=0;f<50;f++)d+="                    ";function g(h,k,i){return h.substr(0,k)+d.substr(0,i)+h.substr(k+1,h.length)}return a=e.utils.eachLine(a,function(h){if(h.indexOf(c)==-1)return h;for(var k=0;(k=h.indexOf(c))!=-1;){var i=b-k%b;h=g(h,k,i)}return h})},fixInputString:function(a){var b=/<br\s*\/?>|&lt;br\s*\/?&gt;/gi;if(e.config.bloggerMode==true)a=a.replace(b,"\n");if(e.config.stripBrs==true)a=a.replace(b,"");return a},trim:function(a){return a.replace(/^\s+|\s+$/g,
"")},unindent:function(a){for(var b=e.utils.fixInputString(a).split("\n"),c=/^\s*/,d=1000,f=0;f<b.length&&d>0;f++){var g=b[f];if(e.utils.trim(g).length!=0){g=c.exec(g);if(g==null)return a;d=Math.min(g[0].length,d)}}if(d>0)for(f=0;f<b.length;f++)b[f]=b[f].substr(d);return b.join("\n")},matchesSortCallback:function(a,b){if(a.index<b.index)return-1;else if(a.index>b.index)return 1;else if(a.length<b.length)return-1;else if(a.length>b.length)return 1;return 0},getMatches:function(a,b){function c(h,k){return[new e.Match(h[0],
h.index,k.css)]}for(var d=null,f=[],g=b.func?b.func:c;(d=b.regex.exec(a))!=null;)f=f.concat(g(d,b));return f},processUrls:function(a){var b="&lt;",c="&gt;";return a.replace(e.regexLib.url,function(d){var f="",g="";if(d.indexOf(b)==0){g=b;d=d.substring(b.length)}if(d.indexOf(c)==d.length-c.length){d=d.substring(0,d.length-c.length);f=c}return g+'<a href="'+d+'">'+d+"</a>"+f})},getSyntaxHighlighterScriptTags:function(){for(var a=document.getElementsByTagName("script"),b=[],c=0;c<a.length;c++)a[c].type==
"syntaxhighlighter"&&b.push(a[c]);return b},stripCData:function(a){var b="<![CDATA[",c="]]\>",d=e.utils.trim(a),f=false;if(d.indexOf(b)==0){d=d.substring(b.length);f=true}if(d.indexOf(c)==d.length-c.length){d=d.substring(0,d.length-c.length);f=true}return f?d:a}},highlight:function(a,b){function c(n){for(var j=[],o=0;o<n.length;o++)j.push(n[o]);return j}b=b?[b]:c(document.getElementsByTagName(e.config.tagName));var d="innerHTML",f=null,g=e.config;if(g.useScriptTags)b=b.concat(e.utils.getSyntaxHighlighterScriptTags());
if(b.length!==0)for(var h=0;h<b.length;h++){var k=b[h],i=e.utils.parseParams(k.className),m,l;i=e.utils.merge(a,i);m=i.brush;if(m!=null){if(i["html-script"]=="true"||e.defaults["html-script"]==true){f=new e.HtmlScript(m);m="htmlscript"}else if(f=e.utils.findBrush(m)){m=f.name;f=new f}else continue;l=k[d];if(g.useScriptTags)l=e.utils.stripCData(l);i["brush-name"]=m;f.highlight(l,i);i=f.div;if(e.config.debug){i=document.createElement("textarea");i.value=f.div.innerHTML;i.style.width="70em";i.style.height=
"30em"}k.parentNode.replaceChild(i,k)}}},all:function(a){e.utils.addEvent(window,"load",function(){e.highlight(a)})}};e.Match=function(a,b,c){this.value=a;this.index=b;this.length=a.length;this.css=c;this.brushName=null};e.Match.prototype.toString=function(){return this.value};e.HtmlScript=function(a){var b=e.utils.findBrush(a),c,d=new e.brushes.Xml;if(b!=null){function f(h){for(var k=h.code,i=[],m=c.regexList,l=h.index+h.left.length,n=c.htmlScript,j,o=0;o<m.length;o++){j=e.utils.getMatches(k,m[o]);
g(j,l);i=i.concat(j)}if(n.left!=null&&h.left!=null){j=e.utils.getMatches(h.left,n.left);g(j,h.index);i=i.concat(j)}if(n.right!=null&&h.right!=null){j=e.utils.getMatches(h.right,n.right);g(j,h.index+h[0].lastIndexOf(h.right));i=i.concat(j)}for(h=0;h<i.length;h++)i[h].brushName=b.name;return i}function g(h,k){for(var i=0;i<h.length;i++)h[i].index+=k}c=new b;this.xmlBrush=d;c.htmlScript==null?e.utils.alert(e.config.strings.brushNotHtmlScript+a):d.regexList.push({regex:c.htmlScript.code,func:f})}};e.HtmlScript.prototype.highlight=
function(a,b){this.xmlBrush.highlight(a,b);this.div=this.xmlBrush.div};e.Highlighter=function(){};e.Highlighter.prototype={getParam:function(a,b){a=this.params[a];return e.utils.toBoolean(a==null?b:a)},create:function(a){return document.createElement(a)},findMatches:function(a,b){var c=[];if(a!=null)for(var d=0;d<a.length;d++)if(typeof a[d]=="object")c=c.concat(e.utils.getMatches(b,a[d]));return c.sort(e.utils.matchesSortCallback)},removeNestedMatches:function(){for(var a=this.matches,b=0;b<a.length;b++)if(a[b]!==
null)for(var c=a[b],d=c.index+c.length,f=b+1;f<a.length&&a[b]!==null;f++){var g=a[f];if(g!==null)if(g.index>d)break;else if(g.index==c.index&&g.length>c.length)this.matches[b]=null;else if(g.index>=c.index&&g.index<d)this.matches[f]=null}},createDisplayLines:function(a){var b=a.split(/\n/g),c=parseInt(this.getParam("first-line")),d=this.getParam("pad-line-numbers"),f=this.getParam("highlight",[]),g=this.getParam("gutter");a="";if(d==true)d=(c+b.length-1).toString().length;else if(isNaN(d)==true)d=
0;for(var h=0;h<b.length;h++){var k=b[h],i=/^(&nbsp;|\s)+/.exec(k),m="alt"+(h%2==0?1:2),l=e.utils.padNumber(c+h,d),n=e.utils.indexOf(f,(c+h).toString())!=-1,j=null;if(i!=null){j=i[0].toString();k=k.substr(j.length)}k=e.utils.trim(k);if(k.length==0)k="&nbsp;";if(n)m+=" highlighted";a+='<div class="line '+m+'"><table><tr>'+(g?'<td class="number"><code>'+l+"</code></td>":"")+'<td class="content">'+(j!=null?'<code class="spaces">'+j.replace(" ","&nbsp;")+"</code>":"")+k+"</td></tr></table></div>"}return a},
processMatches:function(a,b){var c=0,d="",f=e.utils.decorate,g=this.getParam("brush-name","");function h(l){return(l=l?l.brushName||g:g)?l+" ":""}for(var k=0;k<b.length;k++){var i=b[k],m;if(!(i===null||i.length===0)){m=h(i);d+=f(a.substr(c,i.index-c),m+"plain")+f(i.value,m+i.css);c=i.index+i.length}}d+=f(a.substr(c),h()+"plain");return d},highlight:function(a,b){var c=e.vars;this.params={};this.bar=this.code=this.lines=this.div=null;this.toolbarCommands={};this.id=e.utils.guid("highlighter_");c.highlighters[this.id]=
this;if(a===null)a="";this.params=e.utils.merge(e.defaults,b||{});if(this.getParam("light")==true)this.params.toolbar=this.params.gutter=false;this.div=b=this.create("DIV");this.lines=this.create("DIV");this.lines.className="lines";className="syntaxhighlighter";b.id=this.id;if(this.getParam("collapse"))className+=" collapsed";if(this.getParam("gutter")==false)className+=" nogutter";if(this.getParam("wrap-lines")==false)this.lines.className+=" no-wrap";className+=" "+this.getParam("class-name");className+=
" "+this.getParam("brush-name");b.className=className;this.originalCode=a;this.code=e.utils.trimFirstAndLastLines(a).replace(/\r/g," ");a=this.getParam("tab-size");this.code=this.getParam("smart-tabs")==true?e.utils.processSmartTabs(this.code,a):e.utils.processTabs(this.code,a);this.code=e.utils.unindent(this.code);if(this.getParam("toolbar")){this.bar=this.create("DIV");this.bar.className="bar";this.bar.appendChild(e.toolbar.create(this));b.appendChild(this.bar);var d=this.bar;function f(){d.className=
d.className.replace("show","")}b.onmouseover=function(){f();d.className+=" show"};b.onmouseout=function(){f()}}b.appendChild(this.lines);this.matches=this.findMatches(this.regexList,this.code);this.removeNestedMatches();a=this.processMatches(this.code,this.matches);a=this.createDisplayLines(e.utils.trim(a));if(this.getParam("auto-links"))a=e.utils.processUrls(a);this.lines.innerHTML=a},getKeywords:function(a){a=a.replace(/^\s+|\s+$/g,"").replace(/\s+/g,"|");return"\\b(?:"+a+")\\b"},forHtmlScript:function(a){this.htmlScript=
{left:{regex:a.left,css:"script"},right:{regex:a.right,css:"script"},code:new XRegExp("(?<left>"+a.left.source+")(?<code>.*?)(?<right>"+a.right.source+")","sgi")}}};return e}();
window.XRegExp||function(){var e={exec:RegExp.prototype.exec,match:String.prototype.match,replace:String.prototype.replace,split:String.prototype.split},a={part:/(?:[^\\([#\s.]+|\\(?!k<[\w$]+>|[pP]{[^}]+})[\S\s]?|\((?=\?(?!#|<[\w$]+>)))+|(\()(?:\?(?:(#)[^)]*\)|<([$\w]+)>))?|\\(?:k<([\w$]+)>|[pP]{([^}]+)})|(\[\^?)|([\S\s])/g,replaceVar:/(?:[^$]+|\$(?![1-9$&`']|{[$\w]+}))+|\$(?:([1-9]\d*|[$&`'])|{([$\w]+)})/g,extended:/^(?:\s+|#.*)+/,quantifier:/^(?:[?*+]|{\d+(?:,\d*)?})/,classLeft:/&&\[\^?/g,classRight:/]/g};
function b(f,g,h){for(h=h||0;h<f.length;h++)if(f[h]===g)return h;return-1}var c=/()??/.exec("")[1]!==undefined,d={};XRegExp=function(f,g){if(f instanceof RegExp){if(g!==undefined)throw TypeError("can't supply flags when constructing one RegExp from another");return f.addFlags()}g=g||"";var h=g.indexOf("s")>-1,k=g.indexOf("x")>-1,i=false,m=[],l=[],n=a.part,j,o;for(n.lastIndex=0;j=e.exec.call(n,f);)if(j[2])a.quantifier.test(f.slice(n.lastIndex))||l.push("(?:)");else if(j[1]){m.push(j[3]||null);if(j[3])i=
true;l.push("(")}else if(j[4]){o=b(m,j[4]);l.push(o>-1?"\\"+(o+1)+(isNaN(f.charAt(n.lastIndex))?"":"(?:)"):j[0])}else if(j[5])l.push(d.unicode?d.unicode.get(j[5],j[0].charAt(1)==="P"):j[0]);else if(j[6])if(f.charAt(n.lastIndex)==="]"){l.push(j[6]==="["?"(?!)":"[\\S\\s]");n.lastIndex++}else{o=XRegExp.matchRecursive("&&"+f.slice(j.index),a.classLeft,a.classRight,"",{escapeChar:"\\"})[0];l.push(j[6]+o+"]");n.lastIndex+=o.length+1}else if(j[7])if(h&&j[7]===".")l.push("[\\S\\s]");else if(k&&a.extended.test(j[7])){j=
e.exec.call(a.extended,f.slice(n.lastIndex-1))[0].length;a.quantifier.test(f.slice(n.lastIndex-1+j))||l.push("(?:)");n.lastIndex+=j-1}else l.push(j[7]);else l.push(j[0]);g=RegExp(l.join(""),e.replace.call(g,/[sx]+/g,""));g._x={source:f,captureNames:i?m:null};return g};XRegExp.addPlugin=function(f,g){d[f]=g};RegExp.prototype.exec=function(f){var g=e.exec.call(this,f),h;if(g){if(c&&g.length>1){f=new RegExp("^"+this.source+"$(?!\\s)",this.getNativeFlags());e.replace.call(g[0],f,function(){for(h=1;h<
arguments.length-2;h++)if(arguments[h]===undefined)g[h]=undefined})}if(this._x&&this._x.captureNames)for(h=1;h<g.length;h++)if(f=this._x.captureNames[h-1])g[f]=g[h];this.global&&this.lastIndex>g.index+g[0].length&&this.lastIndex--}return g}}();RegExp.prototype.getNativeFlags=function(){return(this.global?"g":"")+(this.ignoreCase?"i":"")+(this.multiline?"m":"")+(this.extended?"x":"")+(this.sticky?"y":"")};
RegExp.prototype.addFlags=function(e){e=new XRegExp(this.source,(e||"")+this.getNativeFlags());if(this._x)e._x={source:this._x.source,captureNames:this._x.captureNames?this._x.captureNames.slice(0):null};return e};RegExp.prototype.call=function(e,a){return this.exec(a)};RegExp.prototype.apply=function(e,a){return this.exec(a[0])};XRegExp.cache=function(e,a){var b="/"+e+"/"+(a||"");return XRegExp.cache[b]||(XRegExp.cache[b]=new XRegExp(e,a))};
XRegExp.escape=function(e){return e.replace(/[-[\]{}()*+?.\\^$|,#\s]/g,"\\$&")};
XRegExp.matchRecursive=function(e,a,b,c,d){d=d||{};var f=d.escapeChar;d=d.valueNames;c=c||"";var g=c.indexOf("g")>-1,h=c.indexOf("i")>-1,k=c.indexOf("m")>-1,i=c.indexOf("y")>-1;c=c.replace(/y/g,"");a=a instanceof RegExp?a.global?a:a.addFlags("g"):new XRegExp(a,"g"+c);b=b instanceof RegExp?b.global?b:b.addFlags("g"):new XRegExp(b,"g"+c);c=[];var m=0,l=0,n=0,j=0,o,p,q;if(f){if(f.length>1)throw SyntaxError("can't supply more than one escape character");if(k)throw TypeError("can't supply escape character when using the multiline flag");
q=XRegExp.escape(f);q=new RegExp("^(?:"+q+"[\\S\\s]|(?:(?!"+a.source+"|"+b.source+")[^"+q+"])+)+",h?"i":"")}for(;1;){a.lastIndex=b.lastIndex=n+(f?(q.exec(e.slice(n))||[""])[0].length:0);h=a.exec(e);k=b.exec(e);if(h&&k)if(h.index<=k.index)k=null;else h=null;if(h||k){l=(h||k).index;n=(h?a:b).lastIndex}else if(!m)break;if(i&&!m&&l>j)break;if(h){if(!m++){o=l;p=n}}else if(k&&m){if(!--m){if(d){d[0]&&o>j&&c.push([d[0],e.slice(j,o),j,o]);d[1]&&c.push([d[1],e.slice(o,p),o,p]);d[2]&&c.push([d[2],e.slice(p,
l),p,l]);d[3]&&c.push([d[3],e.slice(l,n),l,n])}else c.push(e.slice(p,l));j=n;if(!g)break}}else{a.lastIndex=b.lastIndex=0;throw Error("subject data contains unbalanced delimiters");}l===n&&n++}g&&!i&&d&&d[0]&&e.length>j&&c.push([d[0],e.slice(j),j,e.length]);a.lastIndex=b.lastIndex=0;return c};
